import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEventStore } from "./store/eventStore";
import { eventStatus } from "./lib/actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FPL RSC App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const stateCurrentEvent = useEventStore.getState().currentEvent;

  // TODO: Store in a utility file for re-use. Same in Player Page file.
  if (!stateCurrentEvent) {
    const currentEvent = await eventStatus();

    if (!useEventStore.getState().currentEvent) {
      useEventStore.setState(() => ({
        currentEvent,
      }));
    }
  }

  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>{children}</body>
    </html>
  );
}
